"""
This type stub file was generated by pyright.
"""

import logging
from google.auth import version as google_auth_version
from google.auth._default import default, load_credentials_from_file

"""Google Auth Library for Python."""
__version__ = ...
__all__ = ["default", "load_credentials_from_file"]
