"""
This type stub file was generated by pyright.
"""

from google.auth.compute_engine.credentials import Credentials, IDTokenCredentials

"""Google Compute Engine authentication."""
__all__ = ["Credentials", "IDTokenCredentials"]
